[database]
typedb = "postgreSQL" # Only postgreSQL for the moment
host = "localhost"
port = 5432
username = "postgres"
password = "root"
database = "RustyDB"

[server]
maxUser = 30
timeout = 10000 #(ms)
